# Generated by Django 5.1.5 on 2025-01-28 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_comic_usuario_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='id_genero',
        ),
    ]
