# Generated by Django 5.1.5 on 2025-01-29 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_remove_usuario_id_genero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='confirmar_contraseña',
        ),
    ]
